import { Router } from 'express';
import { authLimiter, aiLimiter } from '@middleware/rateLimiter';

import assessmentRouter from './assessment.routes';
import careersRouter from './careers.routes';
import roadmapRouter from './roadmap.routes';
import insightsRouter from './insights.routes';
import chatRouter from './chat.routes';
import jobsRouter from './jobs.routes';
import demoRouter from './demo.routes';
import marketRouter from './market.routes';
import scholarshipsRouter from './scholarships.routes';
import authRouter from './auth.routes';
import userRouter from './user.routes';
import interviewRouter from './interview.routes';
import interviewEnhancedRouter from './interviewEnhanced.routes';
import portfolioRouter from './portfolio.routes';
import linkedinRouter from './linkedin.routes';
import learningEnhancedRouter from './learningEnhanced.routes';
import nsqfRouter from './nsqf.routes';
import featuresRouter from './features.routes';
import profileRouter from './profile.routes';
import billingRouter from './billing.routes';
import adminRouter from './admin.routes';
import referralRouter from './referral.routes';

const router = Router();

router.use('/auth', authLimiter, authRouter);
router.use('/billing', authLimiter, billingRouter);
router.use('/admin', adminRouter);
router.use('/referral', referralRouter);
router.use('/assessment', assessmentRouter);
router.use('/careers', careersRouter);
router.use('/roadmap', roadmapRouter);
router.use('/insights', insightsRouter);
router.use('/chat', aiLimiter, chatRouter);
router.use('/jobs', jobsRouter);
router.use('/market', marketRouter);
router.use('/scholarships', scholarshipsRouter);
router.use('/demo', demoRouter);
router.use('/user', userRouter);
router.use('/interview', aiLimiter, interviewRouter);
router.use('/interview-enhanced', aiLimiter, interviewEnhancedRouter);
router.use('/portfolio', portfolioRouter);
router.use('/linkedin', linkedinRouter);
router.use('/learning-enhanced', learningEnhancedRouter);
router.use('/nsqf', nsqfRouter);
router.use('/features', aiLimiter, featuresRouter);
router.use('/profile', profileRouter);

export default router;
